SinglePageApp/SinglePageApp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("pages/", include("pages.urls")),
    path("admin/", admin.site.urls),
]

SinglePageApp/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'
urlpatterns = [
    path("", views.index, name='index'),
    path("news", views.news, name='news'),
]

SinglePageApp/pages/views.py
from django.shortcuts import render

from django.http import HttpRequest, HttpResponse, JsonResponse

posts = ['post1', 'post2', 'post3', 'post4', 'post5', 'post6', 
         'post7', 'post8', 'post9', 'post10', 'post11', 'post12', 
         'post13', 'post14', ]

# Create your views here.
def index(request: HttpRequest) -> HttpResponse:
    # return HttpResponse('Hello, Kasym! It will be a scrollable page')
    return render(request, 'pages/index.html')

def news(request: HttpRequest) -> HttpResponse:
    return render(request, 'pages/news.html')

def posts(request: HttpRequest) -> HttpResponse:
    # Get start and end points
    start = int(request.GET.get('start') or 0)
    end = int(request.GET.get('end') or (start + 7))

    # Generate a list of posts:
    data = []
    for i in range(start, end + 1):
        data.append(f'Post #{i}')

    # return render(request, 'pages/news.html', {
    #     'posts': data
    # })
    return JsonResponse({
        "posts": data
    })

SinglePageApp/pages/templates/pages/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>SCrollable Page</title>
        <style>
            div {
                background-color: yellow;
                width: auto;
                height: 70px;
                text-align: center;
                padding: 10px;
            }
            
            a {
                font-family: 'Times New Roman', Times, serif;
                font-size: 30px;
                color: black;
            }
        </style>
    </head>
    <body>
        <div>
            <a href="{% url 'pages:news' %}">Новости</a>
        </div>
    </body>
</html>

SinglePageApp/pages/templates/pages/news.html
<!DOCTYPE html>
<html>
    <head>
        <title>WorkINScience</title>
        <style>
            div {
                background-color: azure;
                width: 500px;
                height: 300px;
                padding: 30px;
            }

            h1 {
                color: black;
                font-family: sans-serif;
                font-size: 50px;
                text-align: center;
            }
        </style>
        <script>

            // Start with first post
            let counter = 1;

            //Load posts 20 at a time
            const quantity = 20;

            document.addEventListener('DOMContentLoaded', load);

            function load() {
                const start = counter;
                const end = start + quantity - 1;
                counter = end + 1;

                //Get new posts and add these posts
                fetch(`/news?start=${start}&end=${end}`)
                .then(response => response.json())
                .then(data => {data.posts.forEach(add_post)});
            }


            function add_post(contents) {
                const post = document.createElement('div');
                post.className = 'post';
                post.innerHTML = contents;

                // Adds a new post into the body
                document.querySelector('#posts').append(post);
            }

            window.onscroll = () => {
                if (window.innerHeight + window.scrollY >= document.body.offsetHeight) {
                    document.querySelector('body').style.background = 'green';
                    if (!document.querySelector('button')) {
                        const btn = document.createElement('button')
                        btn.innerHTML = 'Загрузить еще'
                        document.querySelector('body').append(btn)
                    }
                } else {
                    document.querySelector('body').style.background = 'white';
                    document.querySelector('button').remove()
                }
            };

            // document.addEventListener('DOMContentLoaded', () => {
            //     let counter = 0

            //     if (document.querySelector('button')) {
            //         document.querySelector('button').onclick = () => {

            //         }
            //     }
            // });
        </script>
    </head>
    <body>
        <div id="posts"></div>
    </body>
</html>